trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ci_cd/deployment_config/deploy_config.json

pool: amey-vmpool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Kubernetes Sample Deployment
    pool: amey-vmpool
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: KubectlInstaller@0
      inputs:
        kubectlVersion: 'latest'
    - task: PythonScript@0
      displayName: 'Reading configuration file'
      inputs:
        scriptSource: 'filePath'
        scriptPath: '$(System.DefaultWorkingDirectory)/ci_cd/pipeline_config/read_config.py'
        arguments: --config_file $(System.DefaultWorkingDirectory)/ci_cd/deployment_config/deploy_config.json --action 'apply'
    - task: Kubernetes@0
      displayName: 'Deploy Guestbook Application'
      inputs:
        kubernetesServiceConnection: 'amey-aks-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/$(CONFIG_PATH)/deployment.yaml'
    
    - task: Kubernetes@0
      displayName: 'Deploy Guestbook Application'
      inputs:
        kubernetesServiceConnection: 'amey-aks-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/$(CONFIG_PATH)/service.yaml'
    
    - task: Kubernetes@0
      displayName: 'Deploy Guestbook Application'
      inputs:
        kubernetesServiceConnection: 'amey-aks-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/$(CONFIG_PATH)/ingress.yaml'